language: node_js

node_js:
  - "10"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

env:
  - CXX=g++-4.8

before_install:
  - wget http://www.tortall.net/projects/yasm/releases/yasm-1.3.0.tar.gz
  - tar xvzf yasm-1.3.0.tar.gz && cd yasm*
  - ./configure
  - make
  - sudo make install && cd ..

before_script:
  - "echo 1 | ./chinachu installer"

notifications:
  email: false
